# Welcome to Jekyll!
#
title: Geekle Ai Challenges
email: challenges@geekle.ai
description: >- # this means to ignore newlines until "baseurl:"
  A platform for AI challenges where everyone can leverage and integrate into the contest system. Join our community to test your skills and win exciting prizes!
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username: geekleai
contest_system_url: "" # URL for the contest system (optional)
contest_rules_url: "" # URL for contest rules and guidelines (optional)
contact_email: challenges@geekle.ai # contact email for contest-related queries
# Build settings
theme: minima

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap

paginate: 8
paginate_path: "p/:num"
excerpt_separator: <!--more-->

feed:
  title: challenges.geegle.id
  subtitle: How to Maintain Binary Artifacts
  path: rss.xml

sass:
  style: compressed
  deploy_style: compressed
  compile_in_place: false

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
